# Generated by Django 6.0.1 on 2026-01-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatriculaAutorizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=5, unique=True, verbose_name='Matrícula Permitida')),
                ('nome_aluno', models.CharField(blank=True, help_text='Opcional: Nome para seu controle', max_length=100)),
            ],
        ),
    ]
